name: Run Python Tests


on: 
  workflow_dispatch:
   inputs:
     environment:
       type: multi-choice
       description: select packages
       options: 
       - dev
       - qa
       - staging

 
jobs:
  
  dev:
    runs-on: self-hosted
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: "Install dependencies"
        run: |
          echo "Installing dependencies..."
          # Add commands to install dependencies here
 
  staging:
    runs-on: self-hosted
    needs: dev
    steps:
      - name: "Run tests"
        run: |
          echo "Running tests..."
          # Add commands to run tests here
 
  production:
    runs-on: self-hosted
    needs: staging
    steps:
      - name: "Deploy application"
        run: |
          echo "Deploying application..."
