name: Run Python Tests

on: 
  workflow_dispatch:
   inputs:
     environment:
       type: multi-choice
       description: select packages
       options: 
       - dev
       - qa
       - staging

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    
    - name: Print environment
      run: echo " Running on ${{ github.event.inputs.environment }} "
    - name: Print secret
      run: echo " Secretul este ${{ inputs.environment.secret.NU_SPUNE }} "
