name: Run Python Tests

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        pyhton-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest =
